### ISSUE TITLE
SDaccel segfault when executing GZip from Xilinx Applications (HW emulation)

### ISSUE THREAD

**Issue by traoremp** [Xilinx/Applications#14]
Hello everyone,

 

I am trying to build the GZip example from Xilinx Applications

I was able to successfuly generate the awsxclbin following [these steps](https://github.com/aws/aws-fpga/tree/master/SDAccel#build-the-host-application-and-xilinx-fpga-binary) but I encountered an issue.

My executable will only work one out of several trials resulting in a segfault when failing with output:

```
root:/home/centos/Git/Applications/GZip# ./xil_gzip -i xocc_gZip_app.hw.xilinx_aws-vu9p-f1-04261818_dynamic_5_0.log
xclProbe found 1 FPGA slots with xocl driver running
platform Name: Xilinx
Vendor Name : Xilinx
Found Platform
Found Device=xilinx_aws-vu9p-f1-04261818_dynamic_5_0
XCLBIN File Name: gZip_app
INFO: Importing ./gZip_app.hw.xilinx_aws-vu9p-f1-04261818_dynamic_5_0.awsxclbin
Loading: './gZip_app.hw.xilinx_aws-vu9p-f1-04261818_dynamic_5_0.awsxclbin'
This AFI already loaded. Skip reload!
Successfully skipped reloading of local image.

KT(MBps)	GZip_CR		STATUS		File Size(MB)		File Name

Segmentation fault
```
I used gdb to debug it and found where the segmentation fault was coming from:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6697511 in xocl::device::allocate_buffer_object(xocl::memory*) () from /opt/xilinx/xrt/lib/libxilinxopencl.so
```
I am kind of lost as to why this would be happening.

Does anyone have an idea ?

I am using an f1.2xlarge instance from aws.

 

Best regards.

**Comment by kaliudayxilinx** [comment]
We have tried HW_EMU locally and it passes.

**Comment by traoremp** [comment]
But it does not work on F1 instances. Isn't that what it was designed for ?

**Comment by kaliudayxilinx** [comment]
@traoremp provided a fix can you please retry ?
