### ISSUE TITLE
WebP: Make flow is broken, too many Xilinx internal path references

### ISSUE THREAD

**Issue by ted-xie** [Xilinx/Applications#2]
The compilation scripts for WebP (xocc.sh, Makefile.xocc) reference a lot of Xilinx internal paths. In their current states, the scripts are unusable and require significant modification on the user-side just to get this app up-and-running. Users of your WebP accelerator would greatly appreciate if you could update the scripts and remove the internal references. Thank you!

**Comment by fengx-xilinx** [comment]
xocc.sh and Makefile.xocc have been updated.
