### ISSUE TITLE
HW run fails on 326MB compress 

### ISSUE THREAD

**Issue by WannaBeTinker** [Xilinx/Applications#3]
Testing this code I tried to feed the generated SDAccel_Kernel.tar file into the app and it generates an error

>> ./xil_gzip -i Developer_SDAccel_Kernel.tar

result:
ERROR: Failed to sync 652124160/-5 bytes
terminate called after throwing an instance of 'xrt::error'
  what(): event 3 never submitted
Aborted

Is the sample code constrained in max size?

**Comment by kaliudayxilinx** [comment]
max size supported is 100 MB
