### ISSUE TITLE
Cannot find the correct device in emulation mode using JNI

### ISSUE THREAD

**Issue by yancoo** [Xilinx/Applications#7]
I have already mentioned the issue in the xilinx community, please refer to this link：
https://forums.xilinx.com/t5/SDAccel/Cannot-find-the-correct-device-in-emulation-mode-using-JNI/m-p/885044/highlight/true#M2423

@heeran-xilinx @fengx-xilinx Can you help me solve this issue? Thanks in advance.

Best Regards.
yancoo

**Comment by heeran-xilinx** [comment]
Hi @yancoo ,
I have gone through this forum discussion. You were able to use c++ code but seems like issue is specific JNI which we never tried locally. Let's wait for Allyz response. 

-Heera
